{% set name = "virtue" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-skill/virtue-skill-{{ version }}.tar.gz
  sha256: a17ba6a78925763fda53e4cff87d53f1b2b40f641e62f1945b6f837920d0f2f3

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip >=22.2.2
    - flit >=3.7.1
    - python >=3.7
  run:
    - python >=3.7,<4
    - typer >=0.6.1,<1
    - rich >=12.5.1,<13
    - pluggy >=1.0.0,<2

test:
  imports:
    - virtue
  commands:
    - pip check
    - virtue --version
  requires:
    - pip

about:
  home: http://www.cascode-labs.org/virtue/
  summary: Cadence Virtuoso SKILL++ framework
  dev_url: https://github.com/cascode-labs/virtue
  doc_url: http://www.cascode-labs.org/virtue/
  doc_source_url: https://github.com/cascode-labs/virtue/tree/main/docs/source
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - curtisma
