{% set name = "virtue" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-skill/virtue-skill-{{ version }}.tar.gz
  sha256: d8f4adf26fc7e639f794223c6ee0e3e5cf676fa1128daee4855cf2a1d64fd9e8

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip >=22.2.2
    - flit >=3.7.1
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - virtue
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.cascode-labs.org/virtue/
  summary: Cadence Virtuoso SKILL++ framework
  dev_url: https://github.com/cascode-labs/virtue
  doc_url: http://www.cascode-labs.org/virtue/
  doc_source_url: https://github.com/cascode-labs/virtue/tree/main/docs/source
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - curtisma
